import { z } from 'zod';

export const visualizationSchema = z.object({
  summary: z.string(),
  detected_input_type: z.enum([
    'numeric_summary',
    'time_series',
    'categorical_distribution',
    'comparison_table',
    'correlation',
    'hierarchical',
    'geospatial',
    'text_insights',
    'mixed_dataset',
    'unknown',
  ]),
  confidence: z.number(),
  analysis: z.string(),
  key_insights: z.array(z.string()),
  warnings: z.array(z.string()),
  needs_clarification: z.boolean(),
  clarification_questions: z.array(z.string()),
  datasets: z.array(
    z.object({
      dataset_id: z.string(),
      name: z.string(),
      description: z.string(),
      schema: z.object({
        x_key: z.string().nullable(),
        y_keys: z.array(z.string()),
        category_keys: z.array(z.string()),
        value_keys: z.array(z.string()),
        label_keys: z.array(z.string()),
        date_keys: z.array(z.string()),
      }),
      records: z.array(z.record(z.string(), z.any())),
    }),
  ),
  visualizations: z.array(
    z.object({
      viz_id: z.string(),
      title: z.string(),
      chart_type: z.enum([
        'line',
        'bar',
        'area',
        'pie',
        'donut',
        'scatter',
        'radar',
        'table',
        'composed',
        'kpi',
      ]),
      purpose: z.string(),
      dataset_id: z.string(),
      x_key: z.string().nullable(),
      y_keys: z.array(z.string()),
      series: z.array(z.string()),
      stacked: z.boolean(),
      recharts_hint: z.string(),
      insight: z.string(),
    }),
  ),
});
